### ISSUE TITLE
Case classes with more than 22 fields produce runtime exception

### ISSUE THREAD

**Issue by tobia80** [julienrf/play-products#1]
I don't know if I am using this library properly but I defined a case class with more than 22 fields. Compilation is correct but trying to run the tests that were working, I am getting (MerchantWithDetail is the case class):

java.lang.NoSuchMethodError: play.api.libs.functional.syntax.package$.functionalCanBuildApplicative(Lplay/api/libs/functional/Applicative;)Lplay/api/libs/functional/FunctionalCanBuild;
    at julienrf.products.syntax.package$.functionalCanBuildApplicative(package.scala:25)
    at model.MerchantWithDetail$.<init>(MerchantWithDetail.scala:344)
    at model.MerchantWithDetail$.<clinit>(MerchantWithDetail.scala)
    at controllers.v1.Merchants$$anonfun$show$1$$anonfun$apply$2.apply(Merchants.scala:34)
    at controllers.v1.Merchants$$anonfun$show$1$$anonfun$apply$2.apply(Merchants.scala:33)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)

Should I define a FuncionalCanBuild for the MerchantWithDetail?

Thanks

**Comment by julienrf** [comment]
The error message looks unrelated with the case you are describing.
Is it working even with case classes having less than 22 fields ?

**Comment by tobia80** [comment]
I have cloned the project and created a test with a case class with more than 22 fields.
The message I receive is this one during compilation:

Error:(104, 9) Unable to match arguments with the target constructor parameters. Check that they are in the same order;
 arguments  : shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]]]]]]]]]]]]]]]]]]]]]]
 target type: Big
    ).as[Big]
        ^

Error:(104, 9) not enough arguments for method as: (implicit ma: julienrf.products.MappedAs[shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]]]]]]]]]]]]]]]]]]]]]],Big])play.api.libs.json.Reads[Big].
Unspecified value parameter ma.
    ).as[Big]
        ^

everything works fine if fields are 22.

Am I missing some structure definition to make it working?
